### ISSUE TITLE
Documentation at Terraform is missing possible values for parameters

### ISSUE THREAD

**Issue by JonathanDeul** [SchwarzIT/terraform-provider-stackit#196]
Hi, it would be nice to have a more detailed documentation on the terraform registry.
For example for a [MongoDB Flex instance](https://registry.terraform.io/providers/SchwarzIT/stackit/latest/docs/data-sources/mongodb_flex_instance) it is not clear for some parameters what the possible values are: e.g. for the (machine) type that the possible values are Single, Replica and Sharded.

For example, AWS does a pretty good job: [type](https://registry.terraform.io/?product_intent=terraform#type) - "(Optional) The type of EBS volume. Can be standard, gp2, gp3, io1, io2, sc1 or st1 (Default: gp2)."

**Comment by do87** [comment]
you were looking at data source documentation, the MogoDB flex instance _resource_ does contain more information:
https://registry.terraform.io/providers/SchwarzIT/stackit/latest/docs/resources/mongodb_flex_instance

if there are resources you'd like to have more information on, feel free to open another issue
in general, because of how dynamic some settings are, if you enter a random machine type "x", most of the resources will return a detailed error real-time available options for that field

**Comment by JonathanDeul** [comment]
thanks for the recommendation!
